### ISSUE TITLE
Replacement terminology for "ARG v1" (big) vs "ARG v2" (small)

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#104]
We currently have 2 main SARS-CoV-2 "ARG"s, the larger one which only goes up to mid 2021, and the smaller one which is subsampled and goes up to mid 2022. We switched from "big" vs "small" to "v1" versus "v2" to refer to these tree sequences, but there's probably a nicer description to use. We can throw around some ideas in this issue.

**Comment by hyanwong** [comment]
Here are some ideas:
* "dense" (or "unreduced") vs "subsampled"
* "wide" vs "long"
* "time-limited" vs "sample-limited"

**Comment by szhan** [comment]
I kind of prefer "wide" versus "long".

**Comment by hyanwong** [comment]
Yes, there's something nice and simple about that. We can get Sally's opinion tomorrow too.

**Comment by jeromekelleher** [comment]
"Wide" vs "long" is good, if we can explain the thinking clearly early on.

**Comment by jeromekelleher** [comment]
We don't actually deal with this here (this is where we make the method), so going to close this issue.

**Comment by hyanwong** [comment]
Everyone likes it. So good to close anyway.
