### ISSUE TITLE
"Redundant" unary nodes

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#132]
In https://github.com/jeromekelleher/sc2ts/issues/130#issuecomment-1470438214 the `sample_subgraph(712029)` plot shows 3 inserted (i.e. non-sample) nodes which appear to be completely redundant: 673654, 709942, and 713241:

<img width="511" alt="Screenshot 2023-03-15 at 19 29 34" src="https://user-images.githubusercontent.com/4699014/225421922-9713e3fd-249a-4b65-b95f-52d901b1ef79.png">

<img width="502" alt="Screenshot 2023-03-15 at 19 30 04" src="https://user-images.githubusercontent.com/4699014/225422041-a1b04cf2-b606-4ad3-af42-86c028f15cf7.png">

<img width="247" alt="Screenshot 2023-03-15 at 19 30 17" src="https://user-images.githubusercontent.com/4699014/225422093-8606c787-b0a3-45a5-aff8-52d0233b8b8d.png">

I'm not sure how those come about? Is there a node insertion step I'm not understanding properly here?

**Comment by jeromekelleher** [comment]
Can you show the Report on one of those nodes please?

**Comment by hyanwong** [comment]
Sure: a few bits missing off the screenshot here, e.g. the right path to root, but I think this should have all you need?
<img width="1142" alt="Screenshot 2023-03-16 at 09 43 23" src="https://user-images.githubusercontent.com/4699014/225577822-f7cf4d3e-1f86-4c72-a4fd-48f663e0a0f5.png">
<img width="1040" alt="Screenshot 2023-03-16 at 09 43 39" src="https://user-images.githubusercontent.com/4699014/225577916-6090ebdc-99a1-47e3-acee-006f8c5f3884.png">
<img width="1247" alt="Screenshot 2023-03-16 at 09 43 56" src="https://user-images.githubusercontent.com/4699014/225578042-ad412d49-7eb3-41e0-9dc2-c8aa92091c63.png">

**Comment by hyanwong** [comment]
> Tentatively marking as bug to be fixed in next dev push.

Great, glad I picked up something there

> Might be best to simplify out for Viz purposes if they aren't supported by mutations.

Yes, agree. It's not obvious to me how to simplify out specific nodes while not marking them as samples, and leaving other unary nodes in. The two ways I can imagine doing it are (a) attaching all the non-sample nodes I want to keep to an individual (could even be the same one, just for this purpose), then simplify with `keep_unary_in_individuals=True`, or (b) mark the non-sample nodes to keep as samples, then flip the flags back after simplification.

I guess (a) is the least likely to cause unwanted side effects.

**Comment by hyanwong** [comment]
You also want to retain those that have more than one child (I think, either in a single tree or indeed in any trees?)
