### ISSUE TITLE
Sample QC metadata

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#133]
We should keep track of sample QC in the metadata to help diagnose issues in the ARGs, for example, pre-imputed bases in some samples as discussed in #100.

**Comment by jeromekelleher** [comment]
There's some in there already, can you paste an example in here, so we can discuss what additional info you'd like to add?

**Comment by jeromekelleher** [comment]
Just pick an arbitrary sample an paste in its metadata
