### ISSUE TITLE
Alternative/additional data filtering by HMM cost

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#179]
A strategy worth testing for getting rid of some dodgy sequences and short-term time travellers is to exclude samples that exceed a given HMM cost (say, 10). If done naively, this would exclude all descendants of major VoCs, which is clearly a bad idea. However, if we only filter samples that form a cluster of size one under an attachment path this could work quite well. The idea is that if this really is a new VoC there will soon be multiple samples mapping to the same path, and then we'll add it to the ARG as before.

**Comment by szhan** [comment]
How should HMM cost be defined? The number of mutations directly above the new sample? Somehow combined with the number of path switches too? Also, probably, the max HMM cost set should somehow depend on the MMR value used?

**Comment by jeromekelleher** [comment]
I think we've already computed it somewhere, is it in the sample metadata?

**Comment by szhan** [comment]
At the moment, the HMM cost is computed in a function in `Recombinant` class in `utils.py` (see [here](https://github.com/jeromekelleher/sc2ts/blob/b49a51b8b10e3681b730e5d92e666c89e009fb75/sc2ts/utils.py#L182)). Maybe it is useful to copy and paste the code here for discussion.

```python
@property
def total_cost(self):
    """
    How different is the causal sequence from the rest, roughly?
    """
    fwd = self.hmm_runs["forward"]
    bck = self.hmm_runs["backward"]
    cost_fwd = 3 * (len(fwd.parents) - 1) + len(fwd.mutations)
    cost_bck = 3 * (len(bck.parents) - 1) + len(bck.mutations)
    assert cost_fwd == cost_bck
    return cost_fwd
```

The cost of a copying path for a sample is a function of the number of parents and the number of mutations. The penalty for an additional parent node is three times greater than that of an additional mutation. The hard-coded value for this relative penalty is three. It is related to the current default value of three for MMR (or k), right? Should this ultimately be an adjustable parameter like k?

**Comment by jeromekelleher** [comment]
Yes, you're right, the 3 here is the MMR value and hard-coded.

**Comment by szhan** [comment]
This HMM cost can be viewed as a generalisation of branch parsimony scores used in classical phylogenetic methods (which consider only the mutations/substitutions occurring along a branch), I think?

**Comment by szhan** [comment]
In #187, the HMM cost is used to filter out new samples that:
* Are the sole member in groups of newly attached samples having an identical path and an identical set of reversions.
* Have an HMM cost that exceed a maximum value.

This filtering strategy is not as aggressive as filtering newly attached samples on a case-by-case basis, which may throw out genuine saltational variants. However, it does not prevent identical sample sequences with the same erroneous sampling dates from being added to the ARG.

**Comment by szhan** [comment]
I've only added a couple of tests where the values of `num_mismatches` and `max_hmm_cost` are not the default.

**Comment by szhan** [comment]
Note to self. When `num-mismatches` is set to 3, the lowest HMM cost in the first batch of samples (`01-01-2020`) is 24. And when `max-hmm-cost` is set to anything below 24, it encounters an error where assertion that `node.time = 0` fails. This needs to be investigated.

**Comment by jeromekelleher** [comment]
Yeah, there'll be some issues with bootstrapping here. I'd suggest just accepting everything for the first month, and then starting up with the cost filtering. This is also where having a good starting tree would help.
