### ISSUE TITLE
Subgraph plotting: enhancement for showing mutations

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#180]
It would be nice for `sc2ts.utils.plot_subgraph` to be able to plot the number of mutations as a series of blue bars or perpendicular lines, as in Fig 1 of the sc2ts preprint, as an optional replacement for the current dark red numbers. This is only useful for smaller numbers of mutations per edge, but gives a nicer visual feel for the number of mutations on an edge than a number.

**Comment by jeromekelleher** [comment]
This is out date, the ARG-visualiser is doing this work now
