### ISSUE TITLE
Negative submission delay

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#185]
When looking at the metadata of the samples (reportedly collected in 2020) from the data (version 0.4) from [Hunt et al. (2024)](https://www.biorxiv.org/content/10.1101/2024.04.29.591666v1.full.pdf), I found some instances of negative submission delays.

![Screenshot 2024-05-21 at 09 09 16](https://github.com/jeromekelleher/sc2ts/assets/5580375/553428eb-569d-46c1-ae49-fb01a9a2d3db)

I then noticed that such cases are not being filtered out before inference (see the code [here](https://github.com/jeromekelleher/sc2ts/blob/b49a51b8b10e3681b730e5d92e666c89e009fb75/sc2ts/inference.py#L84)).

Perhaps we should modify the filtering condition with:

```0 <= sample.submission_delay < max_submission_delay```

**Comment by szhan** [comment]
It's not entirely clear to me what the submission dates mean. The submission dates are aggregated from three sources: INSDC, GISAID, and COG UK. I'm not sure if the submission date is the date on which the submitter created a submission entry or the date on which the submitter actually hit the submit button.

**Comment by szhan** [comment]
Just checking some emails, the entries in ENA have `first_created` and `first_public` dates. Here we are taking `first_created` dates as the submission dates.

**Comment by jeromekelleher** [comment]
Probably best to filter negative for now

**Comment by szhan** [comment]
The 2020 trees with and without filtering samples with negative submission delay (n = 633) look very similar overall. I don't see a dramatic decrease in the number of reversions or immediate reversions. Also, the number of recombinants is the same (n = 26).

**Comment by szhan** [comment]
On a related note, I don't think that we are filtering by submission delay with this new Viridian dataset like we did before with the GISAID dataset, because the submission dates are not equivalent. I was just reading Martin's email again, and it seems what we have as submission dates are the dates when submission entries are created on the ENA, not GISAID. I think that it is quite probable that many groups submitted lots of their FastQs to the ENA (much) later than when they submitted their genome sequences to GISAID. This may explain why we filter out so many samples using a threshold of max submission delay of 30 days (as shown above).

I wanted to match the samples in the metadata files that Kat and Martin provided in order to see how different the submission dates are. But Kat's file contains GISAID ids and strain names, whereas Martin's file contains GenBank and ENA accessions.

**Comment by szhan** [comment]
Given the amount of data being excluded using a max submission delay of 30 days, and that the GISAID submission dates and ENA submission dates don't seem equivalent, it makes sense to not rely on submission delay-based filter to exclude probable time travellers. Instead, let's see how much HMM cost will help.

**Comment by szhan** [comment]
I think we have decided to pursue using HMM cost to filter out probable time travellers. There are some signs that the HMM cost strategy helps (e.g., reducing the number of mutations in some 20202 ARGs; see #188). Unless we are going to build ARGs out of GISAID data again, we probably don't need to deal with negative submission delays, so closing this for now.
