### ISSUE TITLE
Store the Sample objects of excluded samples as BLOBs in a SQLite database

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#198]
In #193, the Sample objects of excluded samples are stored pickled Sample objects in files. Not only does this slow down the code due to increased IO, but it is also inconvenient to retrieve and filter excluded samples. A better way is to store the pickled Sample objects as BLOBs in a SQLite database, similar to that used to store sample metadata. To facilitate retrieval and analysis, the database should have at least these columns: (1) sample collection date, (2) a boolean indicating whether the sample is added back, and (3) the date on which the sample is added back.

**Comment by jeromekelleher** [comment]
One more column, which is the same primary key as the sample metadata DB.

**Comment by jeromekelleher** [comment]
First pass of this done in #207
