### ISSUE TITLE
Investigate `max_masked_sites_per_sample` equal to 0

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#206]
The `max_masked_sites_per_sample ` (and `mean_masked_sites_per_sample `) from a `TreeInfo` object obtained from the latest ts is 0. Something is wrong.

**Comment by szhan** [comment]
This is due to a bug introduced in `utils.py` after the sample metadata was expanded to include QC, path, and mutations (see `match_path_ts`).

This can be fixed simply by modifying [this](https://github.com/jeromekelleher/sc2ts/blob/7c110de56094b6a45daa48c563da26f1400747c4/sc2ts/utils.py#L360) to the snippet below.

```python
if "sc2ts" in md:
    qc = md["sc2ts"]["qc"]
```

**Comment by jeromekelleher** [comment]
Ah great. Can you open a PR to fix, so we don't forget? No need for tests or anything (it doesn't interact with #207, so I can just merge quickly)
