### ISSUE TITLE
Add some viridian data to repo for testing

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#208]
It would be good to have a small number of alignments in the repo for end-to-end testing purposes. We'd have to see what's practical. The amount of data stored should be something around 1MB I think.

**Comment by szhan** [comment]
We could just use a random subset of the samples collected in the first few months of the pandemic. Or would we want to something more spread out? It is not really to test whether we could pick up recombinants, but for integration testing, right?

**Comment by jeromekelleher** [comment]
Just for integration testing. A random subset seems ideal.
