### ISSUE TITLE
Assign default value for `num_past_days` in `daily_extend`

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#211]
`num_past_days` is assigned a default value of 0 in `fetch_samples_from_pickle_file`. But `daily_extend` uses it to assign `earliest_date` if no base ts is provided. This leads to a bug. To fix it, the default value of `num_past_days` should be assigned in `daily_extend` instead.

**Comment by jeromekelleher** [comment]
This is done differently in #207
