### ISSUE TITLE
Max mutation parents outlier in Viridian data

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#228]
As of 2021-02-26 we have a max_mutation_parents value of 129, which is clearly pathological. Investigate.

**Comment by jeromekelleher** [comment]
This site is a likely cause:

![21846](https://github.com/user-attachments/assets/4b108520-7efe-495c-9088-7084b8e0008b)

**Comment by szhan** [comment]
Do the reversions tend to happen within Delta lineages?

**Comment by jeromekelleher** [comment]
Confirming that this site is the one with a chain of 128 successive mutations. The mutations with > 2 parents are flip-flopping between C and T.

**Comment by jeromekelleher** [comment]
28271 is the next highest mutation count, and is also likely problematic:

![28271](https://github.com/user-attachments/assets/5eda3035-263a-4291-947c-e17d81755a28)

**Comment by jeromekelleher** [comment]
Note that 28271 showed similar problems in the GISAID data, so seems pretty likely to be problematic and a good candidate for exclusion

**Comment by jeromekelleher** [comment]
The next site with highest mutation count is 27638. This looks different, with consistent flicking back and forth between T and C:

![27638](https://github.com/user-attachments/assets/b638bc66-8ee1-493d-975b-3bcd6b190df7)

**Comment by jeromekelleher** [comment]
27752 seems quite similar:

![27752](https://github.com/user-attachments/assets/2454acfc-aca9-481d-b3b3-20d29a430b14)
