### ISSUE TITLE
Introduce optional missingness filter

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#230]
We're currently adding all alignments into the ARG regardless of how much missingness there is. We currently have a max_masked_sites_per_sample of 6535 (2021-02-26) which seems quite high.

What would be a reasonable threshold for missingness @szhan - say > 10% of sites?

**Comment by szhan** [comment]
I previously set it to a maximum of 800 Ns (~2.67% of the sites), which is roughly equivalent to drop-out of two amplicons. >10% of the sites as Ns seems a bit too lax to me. Maybe we could try a maximum of 1,200 Ns (~4%) instead?

**Comment by szhan** [comment]
For reference, NextClade classifies a sequence as "bad" if it has 3,000 Ns or more (see the online doc [here](https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/06-quality-control.html)). That is ~10% of the sites.

**Comment by szhan** [comment]
But in our GISAID trees, we used sequences with an overall QC score of "good", if I recall correctly? So, the threshold should be lower than 10% of the sites, I think.

**Comment by jeromekelleher** [comment]
I don't really have an opinion here, happy to follow your lead.

**Comment by szhan** [comment]
We could probably follow NextClade here (and cite it). Let's say we want "good" sequences as per NextClade's QC criterion. A good sequence has a QC score from 0 to 29 (inclusive). The score increases linearly as the number of Ns in the sequence increases from 300 to 3000 (slope of 1/27); a sequence is allowed 300 Ns before its QC score goes up. So, a good sequence should have at most 1083 Ns (300 Ns + 783 Ns = 29 * 27). This is ~3.6% of the sites.

**Comment by szhan** [comment]
I should have noted this earlier. Probably a better approach is to allow for a certain number of Ns at the terminal regions of the genome, and then penalise additional Ns in the middle of the genome. The reason is that having small stretches of Ns at the highly conserved termini of the SC2 genome is better than having a stretch of Ns in the Spike gene region.

**Comment by iqbal-lab** [comment]
May/not be useful to you, but our trees improved a lot when we first used samples with ~zero Ns (excluding the two ends of the genome), and then added stuff which had some permissible amount of missingness. This was a consequence of how usher works though, so maybe is no help to you.

**Comment by szhan** [comment]
Before running sc2ts on the entire Viridian dataset, we should check how many samples are filtered out across a range of thresholds for max Ns (tolerating Ns in the termini or not).

**Comment by szhan** [comment]
If we use the NextClade-ish threshold of `max_Ns` of 1100, then we keep 83% of the 2020 samples with full-precision dates.

**Comment by szhan** [comment]
Hmm, looking at the NextClade docs again, their pipeline takes in an input sequence and then apply QC filters on the sequence. Its missing data threshold counts Ns that can occur at problematic sites.

In the counts in the tables above, the 481 problematic sites are already excluded. Let's say a "good" sequence has at most 1,083 Ns (based on how NextClade calculates its missing-ness score). If we consider all the problematic sites as Ns in an input sequence and adjust our `max_Ns` threshold for these sites, then we should allow for at most 602 Ns in the rest of the sequence. That is approx. allowing for at most 600 Ns, which keeps ~73% of the 2020 samples according to the table above.

**Comment by szhan** [comment]
On a related note, at the moment, sc2ts treats ambiguous characters as Ns.

NextClade has a separate QC threshold for mixed sites. If a sequence has more than 10 ambiguous characters, then it is considered "bad".

Also, the NextStrain pipeline does things a bit differently. Apparently, it doesn't check for ambiguous characters, so it is more lax in terms of QC compared to the NextClade pipeline.
