### ISSUE TITLE
Move nextstrain.py to paper repo?

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#250]
There's a module [nextstrain.py](https://github.com/jeromekelleher/sc2ts/blob/main/sc2ts/nextstrain.py) which isn't really used here. It probably belongs in the paper repo, if we're still using it for converting nextstrain formatted trees.

Do you remember how we were using this @hyanwong?

(I'm turning this into a "proper" software project here and trying to clear out unused code)

**Comment by hyanwong** [comment]
We were using this to plot the cophylogeny, I think. It should probably be moved to the paper repo, unless there is a more general use-case for people wanting to compare their own inferred sc2 ARGs to nextstrain trees.
