### ISSUE TITLE
Deduplicate samples in Viridian dataset

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#257]
@hyanwong noticed that some sequences have the same GenBank accession in the latest Viridian trees.

For example, the following GenBank accessions have multiple sequences associated with them (the lists are node IDs in the Viridian trees):
```
MT450919.1 [3, 4]
MT450924.1 [96, 97]
MT582495.1 [168, 171]
OU278785.1 [357504, 357505, 357506, 357507]
OU271390.1 [467179, 467180, 467181, 467182]
OU370835.1 [558419, 558420, 558421, 558422]
```

It turns out that some samples have multiple ENA runs, but a single GenBank accession, associated with them. Each run has an associated assembled sequence. Recall also that runs are referenced by ENA run accessions which are used as unique identifiers (i.e. "strain") in the Viridian trees.

For example, the sample associated with the GenBank accession `MT450919.1` has two runs (or sequences corresponding to nodes 3 and 4), which were done using two different sequencing platforms (Illumina and ONT). The same goes for the samples associated with `MT450924.1` and `MT450924.1`.

In the other three cases, it appears that the same samples got sequenced four times (all using Illumina) for some reason.

Going to the metadata file for the Viridian dataset, there are 1,777 sample accessions (e.g. SAMEA8622575) out of 5,284,064 with multiple ENA run accessions. It is a tiny fraction, but we should identify these run accessions and figure out which to exclude from the ARGs. Probably, the easiest solution is to create a list of replicate runs per sample and exclude them when extracting the sequences from the alignment database while matching.

**Comment by szhan** [comment]
The sequences of those samples with replicate runs should be checked to see if they are all identical and if they all have the same collection date. If so, then we just arbitrarily keep one instance and add the others in the exclusion list. I'm going to check this first. Hopefully, it is that simple. Otherwise, we will have to decide on some arbitrary selection protocol.

**Comment by szhan** [comment]
Just noting that the duplicate sequences Yan listed are in the Viridian trees.

**Comment by szhan** [comment]
I think we can close this now, because (1) the duplicate/replicate sequences from the same samples are in the Viridian trees and (2) there are only a small fraction of the samples having duplicate sequences.

**Comment by iqbal-lab** [comment]
Thanks for highlighting this. We're making an updated tree, with all data to August 2024 (so the assemblies will be available too). Removing dups in the process.

**Comment by szhan** [comment]
In Viridian 0.4, there are 14,933 ENA sample accessions with more than one replicate sequence (ENA run accession). I tried to pick the "best" replicate sequence that has the lowest Viridian_cons_het, the lowest Viridian_N, and the highest Viridian_cons_len (breaking ties by applying the criteria in that order). But tie cannot be broken for 4,497 ENA sample accessions; the simplest thing to do may be to choose one replicate sequence at random for these samples.

**Comment by jeromekelleher** [comment]
Is that much different to just picking the first of each?

**Comment by szhan** [comment]
Yes, I think so. For example, the sample SAMEA6872487 has two replicate sequences, ERR4192734 (1st) and ERR4204448 (2nd). Their Viridian_cons_het values (higher values are associated with presence of mixed strains) are 4 and 0, respectively.

**Comment by szhan** [comment]
Okay, for the samples with no tie breakers, let's just pick the first entry as listed in the metadata file.

**Comment by jeromekelleher** [comment]
How do we get this info into sc2ts? Chuck the duplicates out of the metadata BD? (Easier to redo import?)

I guess the code for doing depuplication etc goes in the paper repo then?

**Comment by szhan** [comment]
Or add a new column saying whether it's the duplicate to keep?

I guess chucking out the duplicates removes the need to add some code to handle them in the imported metadata. So, the latter sgtm.

Makes sense the dedup code goes to the paper repo.

**Comment by jeromekelleher** [comment]
Maybe we could trim down the stuff in the CSV as well while we're at it (#273)? Will save some coding in sc2ts if we just put everything in the DB into the sample metadata.

**Comment by szhan** [comment]
Just a visual sanity check. Adding this a bit late.

![kept_removed_comparison](https://github.com/user-attachments/assets/6c7dc4dc-1a5b-4539-88f1-ad0ccc932496)

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(ncols=3, nrows=2, figsize=(15, 7))

ax[0, 0].set_title('Kept', loc='left')
ax[1, 0].set_title('Removed', loc='left')

ax[0, 0].set_ylabel('Number of entries')
ax[0, 0].hist(kept_md['Viridian_cons_het'], bins=50, log=True)
ax[0, 0].set_xlim(0, 70)

ax[1, 0].set_ylabel('Number of entries')
ax[1, 0].set_xlabel('Viridian_cons_het')
ax[1, 0].hist(excluded_md['Viridian_cons_het'], bins=50, log=True)
ax[1, 0].set_xlim(0, 70)

ax[1, 1].set_xlabel('Viridian_N')
ax[0, 1].hist(kept_md['Viridian_N'], bins=50, log=True)
ax[0, 1].set_xlim(0, 16_000)
ax[1, 1].hist(excluded_md['Viridian_N'], bins=50, log=True)
ax[1, 1].set_xlim(0, 16_000)

ax[1, 2].set_xlabel('Viridian_cons_len')
ax[0, 2].hist(kept_md['Viridian_cons_len'], bins=50, log=True)
ax[0, 2].set_xlim(25_000, 30_000)
ax[1, 2].hist(excluded_md['Viridian_cons_len'], bins=50, log=True)
ax[1, 2].set_xlim(25_000, 30_000);
```
