### ISSUE TITLE
Filter Viridian metadata

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#273]
We should filter down the keys used from the viridian metadata as it's annoyingly bulky. @szhan can you suggest a set of keys to usefully keep to aid regular analysis? We can always join back to an existing metadata file for specific analyses, so doesn't have to be exhaustive.

**Comment by jeromekelleher** [comment]
Maybe we start by listing what we have here already, and see what we want to keep?

**Comment by szhan** [comment]
I think these are sensible to keep:
Sample (ENA sample accession)
strain (ENA run accession)
Platform
Country
date
Viridian_result (PASS or not)
In_Viridian_tree
Viridian_pangolin
Viridian_scorpio
Viridian_cons_het

Non-ambiguous characters are encoded as `MISSING`, as I recall. Maybe `Viridian_cons_het` could come in handy if we run into cases with a relatively high number of non-ambiguous characters that appear oddly attached.

**Comment by jeromekelleher** [comment]
I thought we'd conditioned on ``Viridian_result`` being PASS in our first batch of filtering?

**Comment by szhan** [comment]
Yes, I'm just not sure if that's what we're doing now.

**Comment by jeromekelleher** [comment]
I thought that was why a bunch of sequences that are in the metadata are not in the alignments DB?

**Comment by szhan** [comment]
I actually imported all the downloaded consensus sequences without filtering by info in the metadata file (n = 3960704), which are the sequences that ended up in the Viridian tree. But the metadata file contains info about all the sequences. I think in one of our emails we asked for the sequences in the Viridian tree; hence, the difference.

**Comment by szhan** [comment]
Okay, the deduplicated, trimmed metadata file has been imported using sc2ts `542ef08`, and it's under my folder in the BMRC at `viridian/v0.4/`.
