### ISSUE TITLE
Add data on major clades for QC

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#290]
It would be very helpful to have the actual dates and Pango designations of major outbreaks recorded somewhere in the ``info.py`` module so that we can compare the dates we infer (the date we add the first sample of this lineage) with the accepted date of emergence from the literature. This will be an important sanity check for heuristic tuning and also a good statistic to report in the paper.

@szhan - I think you're on this one?

**Comment by szhan** [comment]
I'm also add the Nextstrain clade name because it should make it easier to relate our findings with those from other groups, particularly the Nextstrain group.

**Comment by jeromekelleher** [comment]
Gamma date looks wrong, it's the Jan 6 2021 according to Wikipedia: https://en.wikipedia.org/wiki/SARS-CoV-2_Gamma_variant

**Comment by szhan** [comment]
Yep, it's probably best to just get from the literature. Also, Alpha may be off by like four months (Sep. instead of May).

**Comment by jeromekelleher** [comment]
Yes, Alpha is miles out. Wikipedia says "November 2020" as first observed?

**Comment by szhan** [comment]
But covlineages says it's in 2020-09-03. https://cov-lineages.org/global_report_B.1.1.7.html

It should be more authoritative. That's why I'm not copying straight from Wiki without checking.

**Comment by szhan** [comment]
The ECDC has the months of the earliest sample all here:
https://www.ecdc.europa.eu/en/covid-19/variants-concern

**Comment by szhan** [comment]
pango_lineage | nextstrain_clade | who_label | classification | ecdc_collection_date_earliest_sample | nextstrain_global_alltime_date_confidence_interval | viridian_tree_node | viridian_tree_mutations
-- | -- | -- | -- | -- | -- | -- | --
B.1.1.7 | 20I | Alpha | voc | 2020-09-01 | (2020-08-18, 2020-11-18) | node_388860 | C5388A;C3267T
B.1.617.2 | 21A | Delta | voc | 2020-12-01 | (2020-04-06, 2020-05-24) | node_53921 | C23012G;T26767C;A28461G;C22995A;C27752T
P.1 | 20J | Gamma | voc | 2020-12-01 | (2020-10-20, 2020-12-21) | node_749721 | C13860T
BA.1 | 21K | Omicron | voc | 2021-11-01 | (2020-09-19, 2020-10-26) | node_456414 | C21762T;C2790T;A11537G;A26530G;T22673C;G23048A;C24130A;C23202A;C24503T;T13195C;C25584T;C15240T;G8393A;C25000T
BA.2 | 21L | Omicron | voc | 2021-11-01 | (2020-08-07, 2021-07-20) | node_583346 | C10198T;T22200G;C17410T;A22786C;C21618T;C19955T;A20055G;C25584T;A22898G;C25000T
BA.4 | 22A | Omicron | voc | 2022-01-01 | (2021-11-15, 2022-04-15) | node_693840 | C28724T
BA.5 | 22B | Omicron | voc | 2022-02-01 | (2021-11-10, 2022-04-29) | node_627843 | T27383A;C27382G



I'm grabbing these columns:
* `ecdc_collection_date_earliest_sample` from the ECDC website (https://www.ecdc.europa.eu/en/covid-19/variants-concern).
* `nextstrain_global_alltime_date_confidence_interval` from the global, all-time open-data Nextstrain tree (accessed 24 Sep. 2024) (https://nextstrain.org/ncov/open/global/all-time).
* `viridian_tree_node` from the Viridian UShER tree (https://doi.org/10.6084/m9.figshare.25713261).
* `viridian_tree_mutations` (directly above the `viridian_tree_node`) also from the Viridian tree.
