### ISSUE TITLE
Examine filtering based on total masked sites

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#319]
It would be helpful if we could do some sample filtering based on the number of sites that we mask in the input alignment. This abstracts out a bunch of details in the input data, and gives us an interpretable number: what fraction of the haplotype that we input to the HMM can be marked as missing data, for us to consider it "good"?

@szhan - can you have a look at one of the recent ARGs (there's a plot_masked_sites_per_sample function in the TreeInfo) to see if we can come up with a reasonable threshold that will get rid of samples that you consider suspicious based on the metadata and other metrics?

**Comment by szhan** [comment]
Yep, will do. This was what I was wanting to do, but got sidetracked looking at other things.

**Comment by jeromekelleher** [comment]
I'm trying various things here in terms of filtering and have no good sense of how much data we're losing. I think we need some plots on the distribution of the number of masked sites in the actual input haplotype (which we're not storing, I think).
