### ISSUE TITLE
Turn off (or remove) window-based site masking

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#322]
Window-based site masking was done initially, because we were following others who did that in order to handle problematic regions of some sample genomes, likely due to bioinformatics errors. Now that the assemblies are much cleaner thanks to Martin/Zam's efforts, we should question what this is really doing.

**Comment by szhan** [comment]
@jeromekelleher Guess the latest results support removing this altogether?

**Comment by jeromekelleher** [comment]
Totally. I'm figuring out the best way to preserve information about sample missingness now in metadata QC
