### ISSUE TITLE
Counting genome-wide mutations above a focal node

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#331]
Doing this helps to look at saltational lineages. By default, it should count the mutational events across all the sites going up to the root, but it could be useful to allow counting up to a specified ancestral node instead.

**Comment by szhan** [comment]
It's pretty easy to do this for all nodes. It's a simple DP problem anyway.

The function takes about 24 sec to get counts for all nodes in a ts with 50,000 samples and 64 trees on my Mac.

If one wants to get the counts for a specific set of nodes, then s/he can just simplify the ts down beforehand, I think.

I'll add some basic tests.

**Comment by jeromekelleher** [comment]
I think this should come down quite a lot with the change I suggested in #335
