### ISSUE TITLE
Update LineageDetails

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#338]
As mentioned here #337, I think we should add Beta and Gamma, as they are pre-Omicron saltational VoCs.

**Comment by szhan** [comment]
Also, are the mutation lists in the LineageDetail objects even useful?

**Comment by jeromekelleher** [comment]
Honestly don't know, haven't had a chance to try and use them yet. Stuff has been getting in ahead of reporting on these VOCs
