### ISSUE TITLE
Performance issue in add_exact_matches

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#374]
This function is quite slow, taking over 40 seconds on days with lots of samples. Will presumably only get worse.

The issue is most likely this loop:
```python
  tables = ts.dump_tables()
    for u in np.where(nodes_num_exact_matches > 0)[0]:
        row = tables.nodes[u]
        md = row.metadata
        if "num_exact_matches" not in md["sc2ts"]:
            md["sc2ts"]["num_exact_matches"] = 0
        md["sc2ts"]["num_exact_matches"] += int(nodes_num_exact_matches[u])
        tables.nodes[u] = row.replace(metadata=md)
```
Here we're replacing the row in the node table with metadata that changes size, which incurs a full rewrite of the metadata column each time. It's a quadratic operation here.

Must be a better way to do it.

**Comment by szhan** [comment]
Why do we have to add "num_exact_matches" to the metadata? Can't we just access this info through `nodes_num_exact_matches `?

**Comment by jeromekelleher** [comment]
We don't actually store the exact matches in the ARG any more, and I thought it would be useful to keep track of the number of exact matches each node gets. Our confidence that a particular internal node was inferred correctly is a lot stronger if there is subsequently a bunch of exact matches to it.

We don't have to do it, but I think it is a useful QC metric to allow us to pick out "good" and "not so good" internal nodes later.

**Comment by szhan** [comment]
Yes, but I mean just store this data as a numpy array rather than metadata, so we skip this code snippet altogether.

**Comment by szhan** [comment]
I guess the length is dynamic as the ARG grows, but can create another double-sized array then copy contents over if bound is hit?

**Comment by jeromekelleher** [comment]
> Yes, but I mean just store this data as a numpy array rather than metadata, so we skip this code snippet altogether.

Where, in the top-level metadata? Could I guess. That would be a quick workaround all right.
