### ISSUE TITLE
Scaling mutation rate in `solve_num_mismatches`

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts#385]
The input probability of mutation is defined to be the probability of mutating to any one other distinct allele. When there is mismatch, the emission probability is defined as `(1 - [number of alleles - 1]* mu)`, but it is currently hard-coded to be `(1 - 4 * mu)` because we are treating gaps as a distinct allele. Since we have now decided to treat gaps as missing data, the emission probability should be `(1 - 3 * mu)` instead.

**Comment by jeromekelleher** [comment]
Also should pass num_alleles=4 to tsinfer.

**Comment by szhan** [comment]
When using `run_match`, this info should be determined from the input ts. It could be extracted from provenance, since `deletions_as_missing` is a parameter of `extend`. Alternatively, it could be part of the top-level metadata of the ts for convenient access.

**Comment by szhan** [comment]
The easiest seems to be to set `num_alleles` to 4 or 5 depending on whether `deletions_as_missing` is set to True or False, respectively.
