### ISSUE TITLE
Should we include site 241

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#400]
Site 241 is currently excluded, but `241T` is a "defining" mutation for B.1 lineages, and therefore for a large number of samples high up in the tree. If it is a borderline-site for exclusion, I reckon we should probably include it. I opened this issue just to track our rationale for including / excluding that particular site

**Comment by jeromekelleher** [comment]
ORF1ab starts at 266, so this is in the "extra-genic" flanks that we're excluding unconditionally.

@szhan - this is your call, that do you think?

**Comment by jeromekelleher** [comment]
I've no problem including stuff outside the genes, but we need to make a decision on this pretty quickly. @szhan - what's your thoughts? If these are phylogenetically useful, then there's not much justification for excluding them?

**Comment by szhan** [comment]
Hmm, we are excluding the 5' and 3' UTRs.

**Comment by szhan** [comment]
As discussed earlier with @jeromekelleher, we are going to redo the run _including_ the UTR sites, and use the resulting ARG to identify problematic sites.

**Comment by jeromekelleher** [comment]
241 is not in the latest batch of 100 problematic sites.
