### ISSUE TITLE
Node 1240908 incorrectly placed in upgma-full-md-30-mm-3-2021-06-30.ts.tsz

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#80]
This sample is being placed on much too short a branch, which would seem to be a result of a chain of reversions. It would be worth unpicking this to see how these reversions got in (i.e., were they place by parsimony during tree building, and if so, would a better tree building alg have done a better job?)

![rogue-b117](https://user-images.githubusercontent.com/2664569/215194547-11c26f6e-3a25-45b1-a70f-054549c0401c.png)

**Comment by hyanwong** [comment]
This is "Kuwait/JAH3090859/2021" as mentioned at https://github.com/jeromekelleher/sc2ts/issues/77#issuecomment-1406963615:
<img width="535" alt="Screenshot 2023-01-27 at 22 47 45" src="https://user-images.githubusercontent.com/4699014/215220584-5fa9f0ae-10de-4499-87f4-78e7c8107f3c.png">
