### ISSUE TITLE
Classifying recombination nodes

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts#95]
We know that a number of our recombination nodes are erroneous, and a number are probably correct. In particular, the ones that are designated by an `Xyy` Pango designation are likely correct.

We should collect a number of metrics on nodes, and possibly run something like a PCA, marking the known "Xyy" points on the plot, to see if the known correct recombinants cluster.

This issue is to track what metrics we could use. Here are some ideas:

* The distance between the two parts of the recombinant (either in terms of branch length, number of nodes, or number of mutations)
* The number / proportion of revertant mutations among the children
* The number of mutations proposed by the HMM (this is in the metadata)
* The consistency of the HMM result when run backwards vs forwards (this is in the node metadata)

Others? I think @a-ignatieva volunteered to help with this too.

**Comment by hyanwong** [comment]
Here I classify the recombinant nodes by distance between recombinant lineages in terms of number of nodes (`d_node`), in terms of branch length distance (`d_time`), in terms of number of mutations on the edges constituting each lineage (`d_mut`), the number of *revertant* mutations (`d_rev`), and the number of mutations just associated with that node (`mutations` - as gleaned from the node metadata).

Known Pango recombinants (XB, XA, etc) are in orange. I stuck the mutation row on a log scale: I can do that for the others too if necessary

![image](https://user-images.githubusercontent.com/4699014/218138289-43ab77ed-d598-496c-a4f4-660c04312123.png)

**Comment by hyanwong** [comment]
Here's a pdf with the X lineages labeled in small bold (zoom in to see them):
[pairplot.pdf](https://github.com/jeromekelleher/sc2ts/files/10709723/pairplot.pdf)

**Comment by hyanwong** [comment]
I'm not sure about the allocation of mango lineages, however. For instance, this is XB (found by using `treeinfo.ti.pango_recombinant_lineages_report()`:

<img width="1210" alt="Screenshot 2023-02-10 at 17 29 32" src="https://user-images.githubusercontent.com/4699014/218157214-e2525b14-0631-4885-9f61-0f7e0d3d96ad.png">

But node 206466 (the one I label XB as a result of the above code) has a *huge* number of mutations in the HMM:

```python
Report for 206466
[{'Imputed_lineage': 'Recombinant',
  'date_added': '2021-03-05',
  'match_info': [{'breakpoints': [0, 22021, 26736, 29904],
    'direction': 'backward',
    'mutations': ['1255A>G',
     '3688C>T',
     '3884C>T',
     '6633C>T',
     '7142A>G',
     '9614A>G',
     '9693C>T',
     '9754A>C',
     '15026C>T',
     '15451G>A',
     '16466C>T',
     '21615T>G',
     '21691C>T',
     '21846C>T',
     '22036A>C',
     '23638C>T',
     '25810T>C',
     '27769C>T',
     '28045C>T',
     '28048G>A',
     '28330A>G',
     '28910A>T'],
    'num_mismatches': 3.0,
    'parents': [10524, 200603, 40628],
    'strain': 'USA/TX-TCH-TCMC03017/2021'},
   {'breakpoints': [0, 23604, 27389, 29904],
    'direction': 'forward',
    'mutations': ['1255A>G',
     '3884C>T',
     '6633C>T',
     '7142A>G',
     '9614A>G',
     '9693C>T',
     '9754A>C',
     '15026C>T',
     '15451G>A',
     '16466C>T',
     '21057C>T',
     '21615T>G',
     '21691C>T',
     '21846C>T',
     '22036A>C',
     '23638C>T',
     '25810T>C',
     '27769C>T',
     '28045C>T',
     '28048G>A',
     '28330A>G',
     '28910A>T'],
    'num_mismatches': 3.0,
    'parents': [12108, 200603, 40628],
    'strain': 'USA/TX-TCH-TCMC03017/2021'}]}]
```

<img width="1169" alt="Screenshot 2023-02-10 at 17 31 58" src="https://user-images.githubusercontent.com/4699014/218157692-e76a5d41-61b0-4c88-9c99-e385686f6ee0.png">


<img width="492" alt="Screenshot 2023-02-10 at 17 32 09" src="https://user-images.githubusercontent.com/4699014/218157734-ee8d62c1-378a-429d-95f6-d86d5fc1f0b6.png">

**Comment by hyanwong** [comment]
Here's number of reversions in the children (x) against (log) number of mutations in the recombinant:

<img width="460" alt="Screenshot 2023-02-10 at 18 09 38" src="https://user-images.githubusercontent.com/4699014/218165079-b5354500-61d8-43fd-9ed7-bfadb9aeeacc.png">


It looks like Pango XAK (mapped to node 555388 in the small TS) is a bit of an outlier here, with many revertants in the children. Again, I think this is probably a poorly identified recombinant, that `treeinfo.pango_recombinant_lineages_report()` has misidentified as the XAK origin.

```python
Report for 555388
[{'Imputed_lineage': 'Recombinant',
  'date_added': '2021-12-14',
  'match_info': [{'breakpoints': [0, 22674, 26060, 29904],
    'direction': 'backward',
    'mutations': ['832T>C',
     '2790C>T',
     '9344C>T',
     '9424A>G',
     '9866C>T',
     '10198C>T',
     '11124T>C',
     '11235T>C',
     '17410C>T',
     '19955C>T',
     '20055A>G',
     '21618C>T',
     '21846T>C',
     '22200T>G',
     '22688A>G',
     '22775G>A',
     '22786A>C',
     '22792C>T',
     '22898A>G',
     '23048A>G',
     '23202A>C',
     '24130A>C',
     '25624C>T',
     '27382G>C',
     '27383A>T',
     '27384T>C'],
    'num_mismatches': 3.0,
    'parents': [544948, 551092, 544948],
    'strain': 'Denmark/DCGC-281594/2021'},
   {'breakpoints': [0, 22674, 26060, 29904],
    'direction': 'forward',
    'mutations': ['832T>C',
     '2790C>T',
     '9344C>T',
     '9424A>G',
     '9866C>T',
     '10198C>T',
     '11124T>C',
     '11235T>C',
     '17410C>T',
     '19955C>T',
     '20055A>G',
     '21618C>T',
     '21846T>C',
     '22200T>G',
     '22688A>G',
     '22775G>A',
     '22786A>C',
     '22792C>T',
     '22898A>G',
     '23048A>G',
     '23202A>C',
     '24130A>C',
     '25624C>T',
     '27382G>C',
     '27383A>T',
     '27384T>C'],
    'num_mismatches': 3.0,
    'parents': [544948, 551092, 544948],
    'strain': 'Denmark/DCGC-281594/2021'}]}]
```

<img width="1199" alt="Screenshot 2023-02-10 at 18 14 51" src="https://user-images.githubusercontent.com/4699014/218166296-47000a3f-1174-46cf-a43f-ad0bb4b2981f.png">

**Comment by jeromekelleher** [comment]
The ``pango_recombinant_lineages_report`` is definitely doing a bad job here as it was written implicitly assuming that there would be a single origin for the pango X lineages. However, it's *much* more complicated than that. I think we need to cluster the X-lineage samples by their closest recombinant and then reason about those. But, that's not terribly simple either because it's still quite messy

**Comment by hyanwong** [comment]
So here’s my best rough triage for believable recombinants: I have classified them into good/bad with good having number of revertants in immediate children < 3, number of mutations in HMM <= 10, num non-revertant mutations between recombinant parent lineages > 60 & time to MRCA < 750 days. Green points are good + pango-labelled. Orange are good + non-Pango-labelled, red are bad + Pango labelled. Red indicates the ones that my  basic classifier misses the ones that are single origin are labelled with an X- designation.

[pairplot.pdf](https://github.com/jeromekelleher/sc2ts/files/10711416/pairplot.pdf)

But this metric, these are the recombinant nodes identified as putative "good" recombinants in the small tree sequence. They haven't been filtered by number of children.

```
705501, 731513, 699692, 730277, 701594, 729195, 703379, 704521,
709978, 711560, 731638, 733196, 716784, 696018, 677977, 696838,
675358, 674332, 637879, 674229, 638733, 743460, 568564, 640831,
642277, 642711, 752475, 751632, 666230, 746426, 652247, 663092,
662363, 661450, 660632, 749143, 657300, 679355, 758580, 756466,
633512, 623069, 213104, 625534, 625706, 659577, 690263, 738307,
687046, 685946, 628825, 685963, 683826, 621567, 633497, 639472,
630214, 609881, 663539, 635896, 638141, 630235, 582054, 677584,
625355
```

[pairplot.pdf](https://github.com/jeromekelleher/sc2ts/files/10710631/pairplot.pdf)

**Comment by hyanwong** [comment]
659577 is the most convincing (to me) of the non-Pango recombinants that I've seen according to my criterion:
<img width="1139" alt="Screenshot 2023-02-11 at 00 21 58" src="https://user-images.githubusercontent.com/4699014/218225765-943012ef-d7d2-481e-989a-423f083b60bf.png">

<img width="863" alt="Screenshot 2023-02-11 at 00 21 47" src="https://user-images.githubusercontent.com/4699014/218225755-c92723b9-2413-435b-9586-2cab42586b45.png">

**Comment by a-ignatieva** [comment]
That one looks slightly messy in that it's a parent of another recombinant node (which has an XZ descendant)? 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/36134434/218260794-99ee827b-8901-4182-9697-47d83f499e94.png">

**Comment by jeromekelleher** [comment]
Big ole recombination hairball on the left path to root for this one:

![657300](https://user-images.githubusercontent.com/2664569/218261586-c722417f-f0ee-4025-9ee2-d982c3687996.png)

**Comment by jeromekelleher** [comment]
This is quite hard I think - perhaps it would be better to focus on the big trees from 2021? The trees are better, and there's less time for genuine recombination hairballs to occur. True we have fewer true positives to check against, but that's OK?

**Comment by jeromekelleher** [comment]
I think this is out of date now, closing
