### ISSUE TITLE
Add date_summary data frame

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#97]
Returns a dataframe with a summary of every day:

1. Number of samples
2. Number of recombinants

We should also add summaries of other types of nodes, but I'm not sure if we've been systematic enough about the "data_added" metadata on all nodes.

Any other information we can usefully add about a given day of data should be included.

**Comment by szhan** [comment]
Maybe also these to help us troubleshoot?

1. Array of submission delay of each sample in the daily batch.
2. Array of number of mutations explaining each sample (not just recombinant samples).
